title: Max's Website
email: maxo.philly@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My professional website for data projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://yummyhopper.github.io/MyWebsite.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
